<a href="https://colab.research.google.com/github/sjh04/Pytorch-Tutorail/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors**

In [1]:
import torch
import numpy as np

### **List**

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

### **Numpy**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.48266626, 0.21169775, 0.43459522, 0.0921578 ],
       [0.55842323, 0.8971849 , 0.5103307 , 0.02736635],
       [0.45407522, 0.52526458, 0.29447226, 0.08300104]])

In [6]:
np1.dtype

dtype('float64')

### **Tensors**

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.7841,  0.5855, -0.8952,  0.2609],
        [ 0.6353, -0.8051,  0.3914,  1.7505],
        [ 1.3471,  0.9410, -0.9365, -0.3799]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4827, 0.2117, 0.4346, 0.0922],
        [0.5584, 0.8972, 0.5103, 0.0274],
        [0.4541, 0.5253, 0.2945, 0.0830]], dtype=torch.float64)